export const TIPOS_ETIQUETAS = [
  {
    key: 'GLITCHER',
    nombre: 'Glitcher',
    etiquetas: [
      { nombre: 'Abuso de bugs', puntaje: 2 },
      { nombre: 'Duplicacion de objetos', puntaje: 2 },
      { nombre: 'Inmunidad a danos / Godmode por exploit', puntaje: 4 },
      { nombre: 'Disparar a traves de estructuras', puntaje: 2 },
      { nombre: 'Velocidad aumentada (speedhack)', puntaje: 2 },
      { nombre: 'Salir de mapa / Explorar fuera de limites', puntaje: 1 },
      { nombre: 'Invencibilidad temporal (exploit)', puntaje: 2 },
    ],
  },
  {
    key: 'GRIFFER',
    nombre: 'Griffer',
    etiquetas: [
      { nombre: 'Abusar de vehiculos/objetos explotables', puntaje: 1 },
      { nombre: 'Spawnkill', puntaje: 1 },
      { nombre: 'Trolleo masivo (interrupcion de partidas)', puntaje: 1 },
      { nombre: 'Sabotaje de partidas', puntaje: 2 },
      { nombre: 'Raideo de servidor / invasion coordinada', puntaje: 4 },
      { nombre: 'Ataque DDoS / dano a infraestructura', puntaje: 5 },
      { nombre: 'Spameo de bots / automatizacion maliciosa', puntaje: 2 },
    ],
  },
  {
    key: 'MODDER',
    nombre: 'Modder',
    etiquetas: [
      { nombre: 'Godmode (hack)', puntaje: 5 },
      { nombre: 'Teleport (hack)', puntaje: 4 },
      { nombre: 'Wallhack / ESP', puntaje: 4 },
      { nombre: 'Aimbot', puntaje: 5 },
      { nombre: 'Explosiones invisibles / efectos no autorizados', puntaje: 2 },
      { nombre: 'Spawnear objetos (manipulacion de economia)', puntaje: 2 },
      { nombre: 'Congelar jugadores (modding)', puntaje: 2 },
      { nombre: 'Kickear de la sesion (modding)', puntaje: 2 },
      { nombre: 'Flood de mensajes / spam tecnico', puntaje: 1 },
      { nombre: 'Manipulacion de datos del juego (cheats avanzados)', puntaje: 4 },
      { nombre: 'Blackscreen', puntaje: 3 },
      { nombre: 'Crash', puntaje: 3 },
    ],
  },
  {
    key: 'ACOSO-RAID',
    nombre: 'Acoso/Hostigamiento',
    etiquetas: [
      { nombre: 'Hostigamiento por chat', puntaje: 1 },
      { nombre: 'Mensajes de odio / discriminacion', puntaje: 2 },
      { nombre: 'Acoso en redes sociales', puntaje: 2 },
      { nombre: 'Acoso grupal / doxxing parcial', puntaje: 3 },
      { nombre: 'Amenazas fuera del juego', puntaje: 5 },
      { nombre: 'Extorsion / suplantacion con fines de dano', puntaje: 5 },
      { nombre: 'Divulgacion de informacion privada (doxxing)', puntaje: 5 },
      { nombre: 'Phishing / ingenieria social', puntaje: 5 },
      { nombre: 'Difamacion grave', puntaje: 2 },
      { nombre: 'Multicuentas / evasion de sanciones', puntaje: 2 },
    ],
  },
];
